### ISSUE TITLE
List existing silvershop implementations

### ISSUE THREAD

**Issue by chillu** [silvershop/silvershop.github.io#2]
We frequently write client proposals where silvershop is cited as an option. It's a lot easier to convince prospective clients if we can list some known use cases. Would you be open to collating some of these on your website? It'll involve getting approval of customers in most cases. You can start with Skinny, since we've already published a case study there: https://www.silverstripe.com/success-stories/listing/skinny-mobile-web-development

**Comment by wilr** [comment]
Done - added under 'Showcase'
